# Generated by Django 5.0.4 on 2024-05-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_alter_account_initial_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Каждый день'), ('weekly', 'Каждую неделю'), ('monthly', 'Каждый месяц'), ('yearly', 'Каждый год')], max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='notification_frequency',
            field=models.CharField(blank=True, choices=[('three_days_before', 'За три дня'), ('one_day_before', 'За день'), ('on_event_day', 'В день события')], max_length=20),
        ),
    ]
