# Generated by Django 5.0.4 on 2024-05-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_transaction_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('I', 'Доход'), ('E', 'Расход'), ('T', 'Перевод')], max_length=100),
        ),
    ]
