# Generated by Django 5.0.4 on 2024-05-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwyd', '0011_settings_vanishing'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='general_currency',
            field=models.CharField(default='rub', max_length=100, verbose_name='Стандартная валюта'),
            preserve_default=False,
        ),
    ]
