# Generated by Django 5.0.4 on 2024-05-15 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_transaction_permanent_alter_category_type'),
        ('hwyd', '0013_alter_settings_general_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='general_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.currency', verbose_name='Стандартная валюта'),
        ),
    ]
